### ISSUE TITLE
Friendly Info Sharing

### ISSUE THREAD

**Issue by metaskills** [dinks/cloudfront-rails#4]
Thanks for the work in this gem. Previously I have used Cloudflare, but wanted a simple solution like [our previous gem](https://github.com/customink/actionpack-cloudflare] but found that we needed to make an API request like this gem does. To that end, we made one inspired by your project work here.

https://github.com/customink/actionpack-cloudfront

This gem takes a different approach by assigning to the results of the API request to `ActionDispatch::Railtie.config.action_dispatch.trusted_proxies`. We also only add the services association with CLOUDFRONT too vs all from the API response. Lastly, we have a simple JSON backup file in case errors happen. We shared your gem in a section of our README. Maybe you could do the same for us? Either way, thanks!

**Comment by dinks** [comment]
Thanks and Ill do this.
