### ISSUE TITLE
Cloudfront::Rails: Got exception: strict_parse() expected a String or IO Object

### ISSUE THREAD

**Issue by avantjustus** [dinks/cloudfront-rails#6]
Version: 0.1.0
Rails version: 4.2.7

Getting this error on this line when parsing the HttParty response: https://github.com/dinks/cloudfront-rails/blob/master/lib/cloudfront/rails/railtie.rb#L37

I believe this should instead be `json = ActiveSupport::JSON.decode resp.body`

**Comment by dinks** [comment]
Sorry in being late (waaaay too late). This is fixed
